# Site settings
title: "CV Cristian Baeza M."
description: "Currículum versión web e imprimible"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Cristian Baeza Mesía"
resume_title:                   "Director creativo"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "macnetized@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "607 294 465"
resume_contact_address:         "Madrid"

resume_header_contact_info:     "la dirección"
display_header_contact_info:    "false"

resume_header_intro: "<p>Diseñador gráfico y director creativo con 10 años de experiencia en proyectos visuales para eventos y campañas. Especializado en branding, marketing digital y estrategias de comunicación, liderando equipos y optimizando procesos de producción. Experto en diseño ferial, asegurando ejecución eficiente y resultados de alta calidad. Dominio de Photoshop, Illustrator, InDesign, Premiere Pro, After Effects y Blender 3D, con conocimientos en HTML5, CSS y Python.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        false
resume_section_skills:          true
resume_section_recognition:     false
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/macnetized"
  # resume_twitter_url:           "insert Facebook URL here"
  resume_dribbble_url:          "https://dribbble.com/CrisWeb"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/cristian-baeza-mesia/"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "insert Facebook URL here"
  # resume_medium_url:            "insert Facebook URL here"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
